# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d194c54a85d48ed38fcc819706bb6f398527c64d267e82821ce67692d0afaeba762eb9f1902a92cc32e7a9ce70e3364ce86853d1f9a1fba7638b84b67e2198bf

test:
  secret_key_base: cc34b167975e1d8e319cb3e92645abc623611c913b25c29599f08adad21ca07922e3227c3e533d6a26eba01b153123de411d836de9ee6cb6d1fbb25a1e9cf168

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
